#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar               main:40:0      \
                top_padding                4              \
                bottom_padding             8              \
                left_padding               8              \
                right_padding              8              \
                window_gap                 10

yabai -m config --space 2 layout bsp

echo "yabai configuration loaded.."