#!/bin/bash

# Load colors from SketchyBar theme system
source "$HOME/.config/borders/colors.sh"

options=(
	style="$BORDER_STYLE"
	width="$BORDER_WIDTH"
	hidpi="$BORDER_HIDPI"
	active_color="$BORDER_ACTIVE_COLOR"
	inactive_color="$BORDER_INACTIVE_COLOR"
	background_color="$BORDER_BACKGROUND_COLOR"
)

borders "${options[@]}"
