#!/bin/bash

# SketchyBar Color Configuration
# Uses a cached flat file for fast loading. Regenerated by theme.sh set.

SETTINGS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_FILE="$SETTINGS_DIR/.theme_cache.sh"

if [ -f "$CACHE_FILE" ]; then
  source "$CACHE_FILE"
else
  # Cache doesn't exist yet, generate it via theme.sh
  source "$SETTINGS_DIR/theme.sh" load
  source "$SETTINGS_DIR/theme.sh" _generate_cache
fi
