"""Markdown Report Generator"""

from pathlib import Path
from datetime import datetime
from typing import Dict


class MarkdownReporter:
    """Generates Markdown reports"""

    def __init__(self, results: Dict):
        self.results = results

    def generate(self, output_path: Path):
        """Generate Markdown report"""
        report = self._build_report()

        with open(output_path, 'w') as f:
            f.write(report)

    def _build_report(self) -> str:
        """Build Markdown content"""
        lines = []

        # Header
        lines.append("# Code Quality Report\n")
        lines.append(f"**Project:** {self.results['project']}\n")

        if self.results['environments']:
            lines.append(f"**Environments:** {', '.join(self.results['environments'])}\n")

        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        lines.append("\n---\n")

        # Summary
        lines.append("## Summary\n")
        summary = self.results['summary']
        lines.append(f"- **Files analyzed:** {summary['files_analyzed']}")
        lines.append(f"- **Files modified:** {summary['files_modified']}")
        lines.append(f"- **Issues found:** {sum(summary['issues'].values())}")

        issues = summary['issues']
        lines.append(f"  - 🔴 Errors: {issues.get('errors', 0)}")
        lines.append(f"  - 🟡 Warnings: {issues.get('warnings', 0)}")
        lines.append(f"  - 🔵 Info: {issues.get('info', 0)}")
        lines.append("")

        # Issues by Category
        if self.results['issues']:
            lines.append("## Issues by Category\n")

            # Group issues
            by_category = {}
            for issue in self.results['issues']:
                cat = issue.get('category', 'unknown')
                if cat not in by_category:
                    by_category[cat] = []
                by_category[cat].append(issue)

            for category, issues_list in by_category.items():
                lines.append(f"### {category.title()} ({len(issues_list)})\n")

                for issue in issues_list[:20]:  # Limit to 20 per category
                    file = issue.get('file', 'unknown')
                    line = issue.get('line', '')
                    msg = issue.get('message', 'No message')

                    severity_icon = {"error": "🔴", "warning": "🟡", "info": "🔵"}.get(
                        issue.get('severity', 'info'), "⚪"
                    )

                    location = f"{file}:{line}" if line else file
                    lines.append(f"- {severity_icon} `{location}` - {msg}")

                if len(issues_list) > 20:
                    lines.append(f"\n*... and {len(issues_list) - 20} more issues*\n")

                lines.append("")

        # Configuration
        if self.results['configurations']:
            lines.append("## Configuration Used\n")

            for config in self.results['configurations']:
                lines.append(f"### {config['environment'].title()}\n")

                for config_type, config_path in config['configs'].items():
                    lines.append(f"- **{config_type}:** `{config_path}`")

                lines.append("")

        # Recommendations
        lines.append("## Recommendations\n")

        if summary['issues']['errors'] > 0:
            lines.append("- ❌ **Critical:** Fix errors before committing")

        if summary['issues']['warnings'] > 10:
            lines.append("- ⚠️ **Review:** Large number of warnings detected")

        if summary['files_modified'] > 0:
            lines.append(f"- ✅ **Applied:** {summary['files_modified']} files were automatically formatted")
        elif summary['issues']['errors'] + summary['issues']['warnings'] > 0:
            lines.append("- 💡 **Tip:** Run with `--mode format` to auto-fix formatting issues")

        lines.append("")
        lines.append("---")
        lines.append("\n*Generated by Formatter & Linter Expert*\n")

        return "\n".join(lines)
